version: '3.9'
services:
  postgres:
    image: postgres:15  # Use the desired PostgreSQL version
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: your_username       # Replace with your PostgreSQL username
      POSTGRES_PASSWORD: your_password   # Replace with your PostgreSQL password
      POSTGRES_DB: moneymanager          # Replace with your desired database name
    ports:
      - "5432:5432"  # Map PostgreSQL to the local machine
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage

volumes:
  postgres_data:
